const API_BASE = 'http://localhost:9090/';
const PAGE_LOADER = 'global/PAGE_LOADER';
const GET_SUGGESTIONS = 'global/GET_SUGGESTIONS';
const GET_SEARCH_RESULTS = 'global/GET_SEARCH_RESULTS';
const SEARCH_PAGE_LOADING = 'global/SEARCH_PAGE_LOADING';
const EXPERTS_LIST_LOADING = 'global/EXPERTS_LIST_LOADING';
const GET_EXPERTS_LIST = 'global/GET_EXPERTS_LIST';
const MODAL_TOGGLE = 'joiningModal/MODAL_TOGGLE';
const REGISTRATION_MODAL_TOGGLE = 'joiningModal/REGISTRATION_MODAL_TOGGLE';
const SET_G_SIGNUP_PROFILE = 'joiningModal/SET_G_SIGNUP_PROFILE';
const UPDATE_REGISTRATION_STEP = 'joiningModal/UPDATE_REGISTRATION_STEP';
const GET_ALL_COURSES = 'cources/GET_ALL_COURSES';
const LOADING_ALL_COURSE_BY_TEACHER = 'cources/LOADING_ALL_COURSE_BY_TEACHER';
const ALL_COURSE_BY_TEACHER = 'cources/ALL_COURSE_BY_TEACHER';
const SORT_COURSE = 'cources/SORT_COURSE';
const LOADING_COURSE = 'cources/LOADING_COURSE';
const GET_COURSE_BY_ID = 'cources/GET_COURSE_BY_ID';
const UPDATING_COURSE = 'cources/UPDATING_COURSE';
const LOADING_TEACHER_DETAILS = 'cources/LOADING_TEACHER_DETAILS';
const GET_TEACHER_DETAILS = 'cources/GET_TEACHER_DETAILS';
const OTP_REQUESTED = 'registration/OTP_REQUESTED';
const OTP_GENERATED = 'registration/OTP_GENERATED';
const REGISTRATION_REQUESTED = 'registration/REGISTRATION_REQUESTED';
const REGISTRATION_STATUS_UPDATE = 'registration/REGISTRATION_STATUS_UPDATE';
const UPDATE_REGISTRATION_ERROR = 'registration/UPDATE_REGISTRATION_ERROR';
const RESET_REGISTRATION_FLOW = 'registration/RESET_REGISTRATION_FLOW';
const REGISTRATION_FLOW_USER_TYPE = 'registration/REGISTRATION_FLOW_USER_TYPE';
const UPDATE_MOBILE_NUMBER = 'registration/UPDATE_MOBILE_NUMBER';
const UPDATE_LOGIN_STATUS = 'registration/UPDATE_LOGIN_STATUS';
const UPDATE_LOGIN_TOKEN = 'registration/UPDATE_LOGIN_TOKEN';
const IMAGE_UPLOADING_STATUS = 'registration/IMAGE_UPLOADING_STATUS';
const IMAGE_UPLOADING_PROGRESS = 'registration/IMAGE_UPLOADING_PROGRESS';
const UPDATE_PROFILE_PHOTO = 'registration/UPDATE_PROFILE_PHOTO';
const UPDATE_USER_INFO = 'registration/UPDATE_USER_INFO';
const USER_INFO_LOADING = 'registration/USER_INFO_LOADING';
const PROFILE_UPDATE_REQUEST = 'registration/PROFILE_UPDATE_REQUEST';
const PROFILE_UPDATE_STATUS = 'registration/PROFILE_UPDATE_STATUS';
const GET_CALENDAR = 'booking/GET_CALENDAR';
const LOADING_CALENDAR = 'booking/LOADING_CALENDAR';
const CREATE_UI_FLEXIBLE_CALENDAR = 'booking/CREATE_UI_FLEXIBLE_CALENDAR';
const RESET_UI_FLEXIBLE_CALENDAR = 'booking/RESET_UI_FLEXIBLE_CALENDAR';
const UI_FLEXIBLE_CALENDAR_SELECTION = 'booking/UI_FLEXIBLE_CALENDAR_SELECTION';
const UPDATE_TEACHER_SLOT_TIME_SELECTION = 'booking/UPDATE_TEACHER_SLOT_TIME_SELECTION';
const SET_ACTIVE_MESSAGE_THREAD = 'booking/SET_ACTIVE_MESSAGE_THREAD';
const LOADING_MESSAGES = 'booking/LOADING_MESSAGES';
const GET_MESSAGES = 'booking/GET_MESSAGES';
const SEND_MESSAGES = 'booking/SEND_MESSAGES';
const MESSAGE_SEND_STATUS = 'booking/MESSAGE_SEND_STATUS';
const GET_MESSAGES_WITH_ID = 'booking/GET_MESSAGES_WITH_ID';
const BOOKING_IN_PROGRESS = 'booking/BOOKING_IN_PROGRESS';
const BOOKING_STATUS = 'booking/BOOKING_STATUS';
const PAYMENT_DETAILS = 'booking/PAYMENT_DETAILS';
const RESET_BOOKING_FLOW = 'booking/RESET_BOOKING_FLOW';
const SHOW_FEEDBACK = 'feedback/SHOW_FEEDBACK';
const TOGGLE_FEEDBACK = 'feedback/TOGGLE_FEEDBACK';
const FEEDBACK_STATUS = 'feedback/FEEDBACK_STATUS';
const GET_NOTIFICATIONS = 'notifications/GET_NOTIFICATIONS';
const GET_EVENTS = 'notifications/GET_EVENTS';
const GET_EVENT_STATUS = 'notifications/GET_EVENT_STATUS';

export {
    PAGE_LOADER,
    GET_SUGGESTIONS,
    GET_SEARCH_RESULTS,
    GET_EXPERTS_LIST,
    EXPERTS_LIST_LOADING,
    SEARCH_PAGE_LOADING,
    API_BASE,
    MODAL_TOGGLE,
    REGISTRATION_MODAL_TOGGLE,
    SET_G_SIGNUP_PROFILE,
    UPDATE_REGISTRATION_STEP,
    GET_ALL_COURSES,
    SORT_COURSE,
    LOADING_COURSE,
    GET_COURSE_BY_ID,
    LOADING_TEACHER_DETAILS,
    GET_TEACHER_DETAILS,
    OTP_REQUESTED,
    OTP_GENERATED,
    REGISTRATION_REQUESTED,
    REGISTRATION_STATUS_UPDATE,
    UPDATE_REGISTRATION_ERROR,
    RESET_REGISTRATION_FLOW,
    REGISTRATION_FLOW_USER_TYPE,
    UPDATE_PROFILE_PHOTO,
    UPDATE_MOBILE_NUMBER,
    UPDATE_LOGIN_STATUS,
    UPDATE_LOGIN_TOKEN,
    IMAGE_UPLOADING_STATUS,
    IMAGE_UPLOADING_PROGRESS,
    UPDATE_USER_INFO,
    USER_INFO_LOADING,
    PROFILE_UPDATE_REQUEST,
    PROFILE_UPDATE_STATUS,
    LOADING_ALL_COURSE_BY_TEACHER,
    ALL_COURSE_BY_TEACHER,
    UPDATING_COURSE,
    GET_CALENDAR,
    LOADING_CALENDAR,
    CREATE_UI_FLEXIBLE_CALENDAR,
    RESET_UI_FLEXIBLE_CALENDAR,
    UI_FLEXIBLE_CALENDAR_SELECTION,
    UPDATE_TEACHER_SLOT_TIME_SELECTION,
    SET_ACTIVE_MESSAGE_THREAD,
    GET_MESSAGES,
    SEND_MESSAGES,
    MESSAGE_SEND_STATUS,
    LOADING_MESSAGES,
    GET_MESSAGES_WITH_ID,
    BOOKING_IN_PROGRESS,
    BOOKING_STATUS,
    PAYMENT_DETAILS,
    RESET_BOOKING_FLOW,
    SHOW_FEEDBACK,
    TOGGLE_FEEDBACK,
    FEEDBACK_STATUS,
    GET_NOTIFICATIONS,
    GET_EVENTS,
    GET_EVENT_STATUS
};